FROM alpine:3.21

RUN mkdir -p /var/lib/mysql /var/run/mysqld && chmod -R 777 /var/run/mysqld

COPY ./conf/my.cnf /etc/my.cnf

RUN apk update && apk add --no-cache mariadb mariadb-client openrc; \
	chown -R mysql:mysql /var/lib/mysql /var/run/mysqld


